## NumPy 기본 : 배열과 벡터 연산

### NumPy ndarray : 다차원 배열 객체

In [2]:
import numpy as np

In [6]:
data = np.random.randn(2,3)

In [7]:
data

array([[ 2.14758166, -0.35043583,  0.2042519 ],
       [-0.7939793 ,  0.91852033, -0.30002688]])

In [8]:
data*10

array([[21.47581664, -3.50435826,  2.04251902],
       [-7.93979299,  9.18520328, -3.00026881]])

In [9]:
data+data

array([[ 4.29516333, -0.70087165,  0.4085038 ],
       [-1.5879586 ,  1.83704066, -0.60005376]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### ndarray 생성하기

In [12]:
data1=[6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [16]:
arr2=np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray의 dtype

In [27]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [28]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1,2,3,4,5])

In [32]:
arr.dtype

dtype('int64')

In [34]:
float_arr = arr.astype(np.float64)

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [37]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [40]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [43]:
int_array = np.arange(10)

In [44]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [45]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### NumPy 배열의 산술 연산

In [46]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [47]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [48]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [49]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [51]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [52]:
arr2=np.array([[0., 4., 1.], [7., 2., 12.]])

In [53]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [54]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

### 색인과 슬라이싱 기초

In [56]:
arr = np.arange(10)

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[5]

5

In [59]:
arr[5:8]

array([5, 6, 7])

In [62]:
arr[5:8]=12

In [63]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [64]:
arr_slice = arr[5:8]

In [65]:
arr_slice

array([12, 12, 12])

In [66]:
arr_slice[1]=12345

In [67]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [68]:
arr_slice[:]=64

In [69]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [71]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [72]:
arr2d[2]

array([7, 8, 9])

In [73]:
arr2d[0][2]

3

In [74]:
arr2d[0,2]

3

In [75]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [76]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
old_values = arr3d[0].copy()

In [79]:
arr3d[0]=42

In [80]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
arr3d[0]=old_values

In [82]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d[1,0]

array([7, 8, 9])

In [84]:
x=arr3d[1]

In [85]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [86]:
x[0]

array([7, 8, 9])

### 슬라이스로 선택하기

In [87]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [88]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [89]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [93]:
arr2d[1, :2]

array([4, 5])

In [95]:
arr2d[:2, 2]

array([3, 6])

In [96]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [97]:
arr2d[:2, 1:]=0

In [98]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])